# file: .github/workflows/show-directory.yml
name: onpush
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
<<<<<<< HEAD
      - uses: actions/setup-node@v4
=======
      - uses: action/setup-node@v4
>>>>>>> d879d713a726d54637b1eae8f2b6e58a27dd35c1
      - run: make setup
      - run: make test
      - run: make lint
      - uses: hexlet-components/hello-from-hexlet-action@release
